version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true
      volumes:
        - ./:/var/www

### Workspace Utilities Container ###########################

    workspace:
      build:
        context: ./laradock/workspace
        args:
          - INSTALL_XDEBUG=true
          - INSTALL_BLACKFIRE=true
          - INSTALL_SOAP=false
          - INSTALL_MONGO=false
          - INSTALL_MSSQL=false
          - INSTALL_NODE=true
          - INSTALL_YARN=false
          - INSTALL_DRUSH=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_V8JS=false
          - COMPOSER_GLOBAL_INSTALL=false
          - INSTALL_WORKSPACE_SSH=false
          - INSTALL_LARAVEL_ENVOY=false
          - INSTALL_LARAVEL_INSTALLER=false
          - INSTALL_DEPLOYER=true
          - INSTALL_LINUXBREW=false
          - INSTALL_MC=false
          - PUID=1000
          - PGID=1000
          - NODE_VERSION=stable
          - YARN_VERSION=latest
          - TZ=CEST
          - BLACKFIRE_CLIENT_ID="12d34f88-4284-4984-9955-54ee54e66807"
          - BLACKFIRE_CLIENT_TOKEN="f85722c6d341a20855ca8521d0e1a14748b664bd49a05aa4c807651baf19bf27"
        dockerfile: "Dockerfile-71"
      volumes_from:
        - applications
      extra_hosts:
        - "dockerhost:10.0.75.1"
      ports:
        - "2211:22"
      tty: true
      networks:
        - frontend
        - backend

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./laradock/php-fpm
        args:
          - INSTALL_XDEBUG=false
          - INSTALL_BLACKFIRE=false
          - INSTALL_SOAP=false
          - INSTALL_MONGO=false
          - INSTALL_MSSQL=false
          - INSTALL_ZIP_ARCHIVE=false
          - INSTALL_BCMATH=true
          - INSTALL_PHPREDIS=false
          - INSTALL_MEMCACHED=false
          - INSTALL_OPCACHE=false
          - INSTALL_EXIF=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_MYSQLI=false
          - INSTALL_TOKENIZER=false
          - INSTALL_INTL=false
          - INSTALL_GHOSTSCRIPT=false
          - INSTALL_LDAP=false
          - INSTALL_SWOOLE=false
        dockerfile: "Dockerfile-71"
      volumes_from:
        - applications
      volumes:
        - ./laradock/php-fpm/php71.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:10.0.75.1"
      environment:
        - PHP_IDE_CONFIG="serverName=benevautfr"
      networks:
        - backend

### PHP Worker Container #####################################

    php-worker:
      build:
        context: ./laradock/php-worker
      volumes_from:
        - applications
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:10.0.75.1"
      networks:
        - backend
      command: php artisan queue:work

### Blackfire Container #################################

    blackfire:
      image: blackfire/blackfire
      environment:
        - BLACKFIRE_SERVER_ID="895eb00b-f29c-4737-a3c4-53c73d0d81bb"
        - BLACKFIRE_SERVER_TOKEN="07ad3ec63e1dba518a6fe22a5c2cc9c190ef519f216126c0b80817c3d3fe0798"
      depends_on:
        - php-fpm
      networks:
        - backend

### Apache Server Container #################################

    apache2:
      build:
        context: ./laradock/apache2
        args:
          - PHP_SOCKET="php-fpm:9000"
      volumes_from:
        - applications
      volumes:
        - ./storage/docker/apache2/logs:/var/log/apache2
        - ./laradock/apache2/sites:/etc/apache2/sites-available
      ports:
        - "8011:80"
        - "4411:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### MySQL Container #########################################

    mysql:
      build:
        context: ./laradock/mysql
      environment:
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ./storage/docker/mysql:/var/lib/mysql
        - ./laradock/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3311:3306"
      networks:
        - backend

### Redis Container #########################################

    redis:
      build: ./laradock/redis
      volumes:
        - ./storage/docker/redis:/data
      ports:
        - "6311:6379"
      networks:
        - backend

### Selenium Container ########################################

    selenium:
      build: ./laradock/selenium
      ports:
        - "4011:4444"
      volumes:
        - /dev/shm:/dev/shm
      networks:
        - frontend

### Laravel Echo Server #######################################
    laravel-echo-server:
      build:
        context: ./laradock/laravel-echo-server
      volumes:
        - ./laradock/laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
      ports:
        - "6011:6001"
      links:
        - redis
      networks:
        - frontend
        - backend

### Mailhog Container #########################################

    mailhog:
      build: ./laradock/mailhog
      ports:
        - "8036:8025"
      networks:
        - backend
        - frontend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

### Volumes Setup #############################################

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
